version: '3.5'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/mysql/
      - ./db.cnf:/etc/mysql/conf.d/db.cnf